In [4]:
import pandas as pd

In [2]:
data = pd.read_csv('NFL Play by Play 2009-2016 (v3).csv')

C:\Users\saina\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362447 entries, 0 to 362446
Columns: 102 entries, Date to Season
dtypes: float64(33), int64(31), object(38)
memory usage: 282.1+ MB

In [4]:
data.columns

Index(['Date', 'GameID', 'Drive', 'qtr', 'down', 'time', 'TimeUnder',
       'TimeSecs', 'PlayTimeDiff', 'SideofField',
       ...
       'yacEPA', 'Home_WP_pre', 'Away_WP_pre', 'Home_WP_post', 'Away_WP_post',
       'Win_Prob', 'WPA', 'airWPA', 'yacWPA', 'Season'],
      dtype='object', length=102)

In [5]:
data.Date

0         2009-09-10
1         2009-09-10
2         2009-09-10
3         2009-09-10
4         2009-09-10
             ...
362442    2017-01-01
362443    2017-01-01
362444    2017-01-01
362445    2017-01-01
362446    2017-01-01
Name: Date, Length: 362447, dtype: object

In [8]:
data.GameID

0         2009091000
1         2009091000
2         2009091000
3         2009091000
4         2009091000
             ...
362442    2017010102
362443    2017010102
362444    2017010102
362445    2017010102
362446    2017010102
Name: GameID, Length: 362447, dtype: int64

In [9]:
data.Drive

0          1
1          1
2          1
3          1
4          1
          ..
362442    20
362443    20
362444    21
362445    21
362446    21
Name: Drive, Length: 362447, dtype: int64

In [10]:
data.Home_WP_post

0         0.546433
1         0.551088
2         0.510793
3         0.461217
4         0.558929
            ...
362442    0.093435
362443    0.034069
362444    0.035708
362445    0.000000
362446    0.000000
Name: Home_WP_post, Length: 362447, dtype: float64

In [11]:
data.describe()

,GameID,Drive,qtr,down,TimeUnder,TimeSecs,PlayTimeDiff,yrdln,yrdline100,ydstogo,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
count,3.624470e+05,362447.000000,362447.000000,308229.000000,362447.000000,362259.000000,362073.000000,361724.000000,361724.000000,362447.000000,...,141713.000000,340504.000000,340504.000000,339087.000000,339087.000000,340454.000000,357630.000000,141709.000000,141491.000000,362447.000000
mean,2.012664e+09,12.347088,2.578231,2.001226,7.386076,1695.234346,20.574649,28.413542,48.616807,7.305236,...,-0.386522,0.533889,0.466561,0.534217,0.466185,0.501311,0.002163,0.015209,-0.010492,2012.522071
std,2.292258e+06,7.168173,1.130259,1.006003,4.642132,1063.065717,18.030486,13.002355,25.161965,4.863445,...,1.972964,0.286415,0.286468,0.288647,0.288694,0.288207,0.045326,0.056422,0.067972,2.290084
min,2.009091e+09,1.000000,1.000000,1.000000,0.000000,-900.000000,0.000000,1.000000,1.000000,0.000000,...,-14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.997214,-0.999881,-0.986673,2009.000000
25%,2.011091e+09,6.000000,2.000000,1.000000,3.000000,778.000000,5.000000,20.000000,30.000000,3.000000,...,-0.964562,0.323129,0.230595,0.319464,0.226867,0.274964,-0.014589,-0.011355,-0.018623,2011.000000
50%,2.013091e+09,12.000000,3.000000,2.000000,7.000000,1800.000000,17.000000,30.000000,49.000000,9.000000,...,0.000000,0.531286,0.469040,0.533689,0.466617,0.504349,0.000000,0.003557,0.000000,2013.000000
75%,2.015091e+09,18.000000,4.000000,3.000000,11.000000,2585.000000,37.000000,39.000000,70.000000,10.000000,...,0.484913,0.770011,0.677566,0.773729,0.681018,0.726995,0.014800,0.035702,0.011371,2015.000000
max,2.017010e+09,35.000000,5.000000,4.000000,15.000000,3600.000000,943.000000,50.000000,99.000000,50.000000,...,9.559834,1.000000,1.000000,1.000000,1.000000,1.000000,0.994848,0.994848,1.000000,2016.000000

In [5]:
data2 = pd.read_csv('Building_Permits.csv')

C:\Users\saina\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
data2

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,NaN,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,NaN,Sutter,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

##

In [7]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 43 columns):
Permit Number                             198900 non-null object
Permit Type                               198900 non-null int64
Permit Type Definition                    198900 non-null object
Permit Creation Date                      198900 non-null object
Block                                     198900 non-null object
Lot                                       198900 non-null object
Street Number                             198900 non-null int64
Street Number Suffix                      2216 non-null object
Street Name                               198900 non-null object
Street Suffix                             196132 non-null object
Unit                                      29479 non-null float64
Unit Suffix                               1961 non-null object
Description                               198610 non-null object
Current Status                            198900 non-null object
Current Status Date                       198900 non-null object
Filed Date                                198900 non-null object
Issued Date                               183960 non-null object
Completed Date                            97191 non-null object
First Construction Document Date          183954 non-null object
Structural Notification                   6922 non-null object
Number of Existing Stories                156116 non-null float64
Number of Proposed Stories                156032 non-null float64
Voluntary Soft-Story Retrofit             35 non-null object
Fire Only Permit                          18827 non-null object
Permit Expiration Date                    147020 non-null object
Estimated Cost                            160834 non-null float64
Revised Cost                              192834 non-null float64
Existing Use                              157786 non-null object
Existing Units                            147362 non-null float64
Proposed Use                              156461 non-null object
Proposed Units                            147989 non-null float64
Plansets                                  161591 non-null float64
TIDF Compliance                           2 non-null object
Existing Construction Type                155534 non-null float64
Existing Construction Type Description    155534 non-null object
Proposed Construction Type                155738 non-null float64
Proposed Construction Type Description    155738 non-null object
Site Permit                               5359 non-null object
Supervisor District                       197183 non-null float64
Neighborhoods - Analysis Boundaries       197175 non-null object
Zipcode                                   197184 non-null float64
Location                                  197200 non-null object
Record ID                                 198900 non-null int64
dtypes: float64(12), int64(3), object(28)
memory usage: 65.3+ MB

In [8]:
data2.Location

0         (37.785719256680785, -122.40852313194863)
1          (37.78733980600732, -122.41063199757738)
2           (37.7946573324287, -122.42232562979227)
3          (37.79595867909168, -122.41557405519474)
4          (37.78315261897309, -122.40950883997789)
                            ...
198895                                          NaN
198896                                          NaN
198897                                          NaN
198898                                          NaN
198899                                          NaN
Name: Location, Length: 198900, dtype: object

In [19]:
len(data2['Current Status'].unique())

14

In [20]:
data2['Current Status']

0           expired
1            issued
2         withdrawn
3          complete
4            issued
            ...
198895       issued
198896       issued
198897       issued
198898       issued
198899       issued
Name: Current Status, Length: 198900, dtype: object

In [21]:
x = data2.iloc[:,13:14].values

In [22]:
x

array([['expired'],
       ['issued'],
       ['withdrawn'],
       ...,
       ['issued'],
       ['issued'],
       ['issued']], dtype=object)

In [ ]:
from sklearn.preprocessing import